
# 필요한 Repo Secret 설정
#### CI
# ${{ secrets.SONARQUBE_URL }} : 소나큐브 서버 URL
# ${{ secrets.SONARQUBE_ACCESS_TOKEN }} : 소나큐브 연결을 위한 액세스 토큰
# ${{ secrets.SUBMODULE_ACCESS_TOKEN }} : 깃허브 액세스 토큰

#### CD
# ${{ secrets.DOCKER_ID }} : 도커허브 id
# ${{ secrets.DOCKER_PASSWORD }} : 도커허브 pw
# ${{ secrets.REMOTE_HOST }} : 배포 서버 HOSTNAME
# ${{ secrets.REMOTE_PORT }} : 배포 서버 PORT
# ${{ secrets.REMOTE_USERNAME }} : 배포 서버 USERNAME
# ${{ secrets.REMOTE_SSH_KEY }} : 배포 서버 연결을 위한 SSH KEY

name: Backend CI & CD

# PR 요청에 대해
on:
  pull_request:
    # 특정 브랜치만
    branches: [develop, main]
    # pr이 생성 되었을 때, 담당 유저가 등록되었을 때, PR에 코드가 머지되었을 때, 라벨이 달렸을 때 동작
    types: [opened, assigned, synchronize, labeled, reopened]
  push:
    branches: [develop, main]

jobs:
  ###### 본문 내용과 관련 없는 Job, 빌드 테스트
  Backend-CI:
    env:
      # KEY - VALUE
      SONARQUBE_ID: jaksim31
      SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
    # macos 환경에서 CI 실행 (환경은 github이 제공)
    runs-on: macos-latest
    # 각 단계
    steps:

      # 소스코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v2
        # 서브모듈 설정
        with:
          submodules: true
          # secrets 변수는 github 세팅에서 미리 세팅한 데이터
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}

      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      # Maven Package Caching
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Grant execute permission for maven
        run: chmod +x mvnw

      #      - name: check
      #        run : |
      #            cat submodule/resources/main/prod/application.yml

      # develop 브랜치일 경우 local 환경 빌드
      - name: (PR) Maven Build (Adding Unit Test & Integration Test)
        if: github.event_name == 'pull_request'
        run: ./mvnw clean install -Dspring.profiles.active=local -P local

      - name: (Push & Develop) Maven Build (Adding Unit Test & Integration Test)
        if: contains(github.ref, 'develop') && github.event_name == 'push'
        run: ./mvnw clean install -Dspring.profiles.active=local -P local

      # main 브랜치에 push 할 경우 prod 환경 빌드
      - name: (Push & Main) Maven Build (Skip Unit Test & Integration Test)
        if: contains(github.ref, 'main') && github.event_name == 'push'
        run: ./mvnw clean install -DskipTests=True -Dspring.profiles.active=prod -P prod

      # main 브랜치에 push 할 경우 CD job에 jar file 업로드
      - name: (Push & Main) Archive production artifacts
        if: github.event_name == 'push' && contains(github.ref, 'main')
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target/*.jar

      - name: (PR) Archive test results artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: test-result
          path: target/surefire-reports/

      - name: (PR) Archive test results artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: classes
          path: target/classes/

  Report-Test-Result:
    if: github.event_name == 'pull_request'
    needs: Backend-CI
    # macos 환경에서 CI 실행 (환경은 github이 제공)
    runs-on: ubuntu-latest
    # 각 단계
    steps:
      # 이전 Job에서 업로드한 Jar file 다운로드
      - name: Download a test result
        uses: actions/download-artifact@v1
        with:
          name: test-result

      - name: check dir
        run: ls -al

      - name: (PR) Write the testing result on PR
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always() && github.event_name == 'pull_request'
        with:
          junit_files: './target/surefire-reports/TEST-*.xml'
          comment_title: 'Jaksim31 Unit & Integration Test Results'

      - name: (PR) Check Comment on the Code line.
        uses: mikepenz/action-junit-report@v3
        if: always() && github.event_name == 'pull_request'
        with:
          report_paths: './target/surefire-reports/TEST-*.xml'
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}


  Sonarqube-Analysis:
    if: github.event_name == 'pull_request'
    needs: Backend-CI
    env:
      # KEY - VALUE
      SONARQUBE_ID: jaksim31
      SONARQUBE_URL: ${{ secrets.SONARQUBE_URL }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      # macos 환경에서 CI 실행 (환경은 github이 제공)
    runs-on: ubuntu-latest
    # 각 단계
    steps:
      # 소스코드 가져오기
      - name: Checkout source code
        uses: actions/checkout@v2
        # 서브모듈 설정
        with:
          submodules: true
          # secrets 변수는 github 세팅에서 미리 세팅한 데이터
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}

      # 이전 Job에서 업로드한 Jar file 다운로드
      - name: Download a test result
        uses: actions/download-artifact@v1
        with:
          name: classes

      - name: check dir
        run: ls -al

      # 위에서 설정했던 정적코드 전송 태스크 실행
      - name: (PR) Sonarqube Analysis
        if: always() && github.event_name == 'pull_request'
        run: ./mvnw sonar:sonar -Dsonar.host.url=${{ env.SONARQUBE_URL }} -Dsonar.projectKey=${{ env.SONARQUBE_ID }} -Dsonar.projectName=${{ env.SONARQUBE_ID }}-${{ env.PR_NUMBER }} -Dsonar.login=${{ secrets.SONARQUBE_ACCESS_TOKEN }}

      - name: (PR) Comment Sonarqube URL
        if: always() && github.event_name == 'pull_request'
        uses: actions/github-script@v4
        with:
          # 이슈에 코멘트를 달아주는 스크립트 실행
          script: |
            const { SONARQUBE_ID, SONARQUBE_URL, PR_NUMBER } = process.env
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📊 ${ SONARQUBE_ID }-${ PR_NUMBER } 정적 코드 분석 결과 확인하기 [링크](${SONARQUBE_URL})`})

  Backend-CD:
    # main 브랜치에 push 하는 경우에만 배포 JOB 실행
    if: github.event_name == 'push' && contains(github.ref, 'main')
    needs: Backend-CI
    runs-on: ubuntu-latest
    steps:

      # 소스코드 가져오기
      - name: Checkout source code
        uses: actions/checkout@v2
        # 서브모듈 설정
        with:
          submodules: true
          # secrets 변수는 github 세팅에서 미리 세팅한 데이터
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}

      # 이전 Job에서 업로드한 Jar file 다운로드
      - name : Download a built Jar File
        uses: actions/download-artifact@v1
        with:
          name: target

      # Docker Buildx Setting
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Docker Login
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_ID }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker Build & Push
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_ID }}/jaksim31-backend:$(date +%s)
            ${{ secrets.DOCKER_ID }}/jaksim31-backend:latest
          cache-from: type=gha    # gha=Github Action Cache
          cache-to: type=gha,mode=max

      - name: Transfer Deploy Script use SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          source: "scripts/deploy.sh"
          target: "/home/centos/deploy"

      # SSH Connect
      - name: Execute Server Init Script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: ${{ secrets.REMOTE_PORT }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script_stop: true
          script: chmod +x /home/centos/deploy/scripts/deploy.sh && sh /home/centos/deploy/scripts/deploy.sh

